### ISSUE TITLE
findOneAndUpdate does not project fields

### ISSUE THREAD

**Issue by JulianMayorga** [Automattic/monk#158]
According to [monk findOneAndUpdate docs](https://automattic.github.io/monk/docs/collection/findOneAndUpdate.html) you can pass an object to options of findOneAndUpdate and it will apply a projection , but according to [mongo findOneAndUpdate docs](https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndUpdate/), you need to pass the fields you want to include/exclude in a projection key.

To clarify what the problem is, here is a query that according to monk's documentation should work but does not:
```
return matches.findOneAndUpdate(
    { _id: match_id },
    { $push: { events: event } },
    { 'home_team.players': 0, 'away_team.players': 0 }
  );
```
And here is a query that works:
```
return matches.findOneAndUpdate(
    { _id: match_id },
    { $push: { events: event } },
    { projection: { 'home_team.players': 0, 'away_team.players': 0 } }
  );
```

**Comment by mathieudutour** [comment]
Monk will not transform an option object to another object, that would be too hard to maintain.
What it does though is transforming a string or an array to an projection object (https://github.com/Automattic/monk/blob/master/test/collection.js#L167).

Maybe the doc is not clear enough?

**Comment by chrispstephens** [comment]
Can this be reopened? While the original poster's example is not supported, the following - as far as I can read in the documentation should:
```js
return matches.findOneAndUpdate(
    { _id: match_id },
    { $push: { events: event } },
    'home_team.players'
  )
```
String do not seem to parsed into projections for findOneAndUpdate.

**Comment by alphanumeric0101** [comment]
Agree with @chrispstephens, this issue is present in monk 6.0.6 at least.

In order to use projection with `findOneAndUpdate` I had to pass

```
{ 
    projection: {
        field1: 1,
        field2: 1
    }
}
```

in as the third param but the docs say I should be able to pass just a string, or an array of strings to the fields property of the options object. Neither of those resulted in projection (entire doc was returned both times), but passing an object like the one above did return only the selected fields.

Projection works as expected in all other find methods that I employ.
