### ISSUE TITLE
Question: How to mock monk?

### ISSUE THREAD

**Issue by ericfong** [Automattic/monk#201]
I am writing test in jest.

Anyone have experience on how to mock monk? 

Thanks a lot

**Comment by mathieudutour** [comment]
That's a really good question.

Usually you don't really need to mock it, you just use a test database, connect to it, do your tests, and remove it at the end.

That being said, jest is annoying because you can't share a database connection (since each test file is run in his own thread), so you need to connect on each file. It's slowing down the tests by quite a lot if you have a lot of different test files.
So mocking monk would be useful in some cases. It's just super hard to have a generic mock, the mongo API is really complex and I didn't find any working mock of mongo.

I'd say that you can mock the part that you are using manually.

Hope that helps

**Comment by ericfong** [comment]
Just for reference. So far, we are using 'mongo-mock' and

```
  jest.mock('mongodb', () => {
    const mongoMock = require('mongo-mock')
    const ObjectId = require('bson-objectid')

    Object.assign(mongoMock, {
      Logger: {
        setCurrentLogger() {},
        setLevel() {},
      },
    })

    // NOTE mongo-mock use getter and setter for ObjectId
    ObjectId.createFromHexString = ObjectId
    mongoMock.ObjectID = ObjectId

    return mongoMock
  })
```

Only test with monk@4.0.0 
If anyone successfully mock monk@5.0.0, please share some code. Thanks

**Comment by mathieudutour** [comment]
The API didn't actually change from 4.0 to 5.0. What's not working on monk@5?

**Comment by ericfong** [comment]
Oh. We just have not yet updated to 5.0.0. so have not tested.
