### ISSUE TITLE
Add support for Mongo 3.6 connection strings

### ISSUE THREAD

**Issue by wiesson** [Automattic/monk#251]
I'm using the MongoDb from https://cloud.mongodb.com/ and the version 3.6 offers me a connection string like this:

`mongodb+srv://foo:myRealPassword@cluster0.mongodb.net/test`

When I try to use it, I simply receive `MongoError: getaddrinfo ENOTFOUND`. Any thoughts? If I switch back to `mongodb://foo:myRealPassword@mycluster0-shard-00-00.mongodb.net:27017,mycluster0-shard-00-01.mongodb.net:27017,mycluster0-shard-00-02.mongodb.net:27017/admin?ssl=true&replicaSet=Mycluster0-shard-0&authSource=admin` it works.

**Comment by Negan1911** [comment]
Same here

**Comment by michaelauderer** [comment]
Same issue for me.. using v3.4 string is working.

**Comment by simranjeet2589** [comment]
The package is still using **"mongodb": "^2.1.18"**, which does not support the new connection string format by mongo.
As per the official mongo docs mentioned [here](https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility), the native driver needs to be updated to v3.0.0 in order to utilise the new DNS Seedlist Connection Format.

**Comment by michaelauderer** [comment]
@simranjeet2589 You're correct. Would it be ideal to update Monk to use MongoDB v3?

**Comment by simranjeet2589** [comment]
@michaelauderer In my opinion Monk should be updated. It is a tiny layer over mongo and it should bring in the new driver to support enhancements and features offered by new version of mongo.
